set(COMPILER_RT_SOURCE_FILES
    builtins/absvdi2.c
    builtins/absvsi2.c
    builtins/absvti2.c
    builtins/adddf3.c
    builtins/addtf3.c
    builtins/addvdi3.c
    builtins/addvsi3.c
    builtins/addvti3.c
    builtins/arm/addsf3.S
    builtins/arm/aeabi_cdcmp.S
    builtins/arm/aeabi_cdcmpeq_check_nan.c
    builtins/arm/aeabi_cfcmp.S
    builtins/arm/aeabi_cfcmpeq_check_nan.c
    builtins/arm/aeabi_dcmp.S
    builtins/arm/aeabi_div0.c
    builtins/arm/aeabi_drsub.c
    builtins/arm/aeabi_fcmp.S
    builtins/arm/aeabi_frsub.c
    builtins/arm/aeabi_idivmod.S
    builtins/arm/aeabi_ldivmod.S
    builtins/arm/aeabi_memcmp.S
    builtins/arm/aeabi_memcpy.S
    builtins/arm/aeabi_memmove.S
    builtins/arm/aeabi_memset.S
    builtins/arm/aeabi_uidivmod.S
    builtins/arm/aeabi_uldivmod.S
    builtins/arm/comparesf2.S
    builtins/arm/divsi3.S
    builtins/arm/udivsi3.S
    builtins/ashldi3.c
    builtins/ashlti3.c
    builtins/ashrdi3.c
    builtins/ashrti3.c
    builtins/bswapdi2.c
    builtins/bswapsi2.c
    builtins/clear_cache.c
    builtins/clzdi2.c
    builtins/clzsi2.c
    builtins/clzti2.c
    builtins/cmpdi2.c
    builtins/cmpti2.c
    builtins/comparedf2.c
    builtins/ctzdi2.c
    builtins/ctzsi2.c
    builtins/ctzti2.c
    builtins/divdc3.c
    builtins/divdf3.c
    builtins/divdi3.c
    builtins/divmoddi4.c
    builtins/divmodsi4.c
    builtins/divsc3.c
    builtins/divsf3.c
    builtins/divtc3.c
    builtins/divtf3.c
    builtins/divti3.c
    builtins/extendhfsf2.c
    builtins/extendsfdf2.c
    builtins/ffsdi2.c
    builtins/ffssi2.c
    builtins/ffsti2.c
    builtins/fixdfdi.c
    builtins/fixdfsi.c
    builtins/fixdfti.c
    builtins/fixsfdi.c
    builtins/fixsfsi.c
    builtins/fixsfti.c
    builtins/fixunsdfdi.c
    builtins/fixunsdfsi.c
    builtins/fixunsdfti.c
    builtins/fixunssfdi.c
    builtins/fixunssfsi.c
    builtins/fixunssfti.c
    builtins/floatdidf.c
    builtins/floatdisf.c
    builtins/floatsidf.c
    builtins/floatsisf.c
    builtins/floattidf.c
    builtins/floattisf.c
    builtins/floatundidf.c
    builtins/floatundisf.c
    builtins/floatunsidf.c
    builtins/floatunsisf.c
    builtins/floatuntidf.c
    builtins/floatuntisf.c
    builtins/fp_mode.c
    builtins/gcc_personality_v0.c
    builtins/int_util.c
    builtins/lshrdi3.c
    builtins/lshrti3.c
    builtins/moddi3.c
    builtins/modsi3.c
    builtins/modti3.c
    builtins/muldc3.c
    builtins/muldf3.c
    builtins/muldi3.c
    builtins/mulodi4.c
    builtins/mulosi4.c
    builtins/muloti4.c
    builtins/mulsc3.c
    builtins/mulsf3.c
    builtins/multf3.c
    builtins/multi3.c
    builtins/mulvdi3.c
    builtins/mulvsi3.c
    builtins/mulvti3.c
    builtins/negdf2.c
    builtins/negdi2.c
    builtins/negsf2.c
    builtins/negti2.c
    builtins/negvdi2.c
    builtins/negvsi2.c
    builtins/negvti2.c
    builtins/paritydi2.c
    builtins/paritysi2.c
    builtins/parityti2.c
    builtins/popcountdi2.c
    builtins/popcountsi2.c
    builtins/popcountti2.c
    builtins/powidf2.c
    builtins/powisf2.c
    builtins/powitf2.c
    builtins/subdf3.c
    builtins/subsf3.c
    builtins/subtf3.c
    builtins/subvdi3.c
    builtins/subvsi3.c
    builtins/subvti3.c
    builtins/truncdfhf2.c
    builtins/truncdfsf2.c
    builtins/truncsfhf2.c
    builtins/ucmpdi2.c
    builtins/ucmpti2.c
    builtins/udivdi3.c
    builtins/udivmoddi4.c
    builtins/udivmodsi4.c
    builtins/udivmodti4.c
    builtins/udivti3.c
    builtins/umoddi3.c
    builtins/umodsi3.c
    builtins/umodti3.c
    builtins/extendbfsf2.c
    builtins/extendxftf2.c
)

list(TRANSFORM COMPILER_RT_SOURCE_FILES PREPEND "${CMAKE_CURRENT_LIST_DIR}/")

set(compiler-rt_flags
    -fno-builtin
    -Wno-pedantic
    -Wno-incompatible-pointer-types
    -Wno-reserved-id-macro
    -Wno-unused-parameter
    -Wno-missing-prototypes
    -Wno-sign-conversion
    -Wno-undef
    -Wno-double-promotion
    -Wno-shorten-64-to-32
    -Wno-float-equal
    -Wno-implicit-int-float-conversion
    -Wno-missing-noreturn
    -Wno-cast-align
    -Wno-implicit-int-conversion
    -Wno-extra-semi-stmt
    -Wno-float-conversion
    -Wno-shift-sign-overflow
    -Wno-unreachable-code-break
    -Wno-unsafe-buffer-usage
    -Wno-visibility
    -Wno-tautological-value-range-compare
    -DVISIBILITY_HIDDEN
    -fvisibility=hidden
    -fno-stack-protector)

list(JOIN compiler-rt_flags " " COMPILER_RT_FLAGS)

set_source_files_properties(
  ${COMPILER_RT_SOURCE_FILES} PROPERTIES COMPILE_FLAGS "${COMPILER_RT_FLAGS}")
